import type { CommandResult } from "@/types/terminal";

const RESUME_LINES = [
  "YURIY TOLSTYKH",
  "Senior Software Engineer — San Jose, CA",
  "408-726-1215  •  github.com/ytolstyk  •  yuriy.tolstykh@gmail.com  •  yuriytolstykh.com",
  "",
  "SUMMARY",
  "  Senior Full-Stack Engineer with 10+ years of experience driving multi-million",
  "  dollar revenue growth through expert API design, high-performance React UIs,",
  "  and AI-driven automation. Expert in bridging complex data systems (Databricks,",
  "  BigQuery) with seamless customer experiences, delivering scalable features that",
  "  serve over 5,000+ enterprise clients. Collaborative technical leader experienced",
  "  in mentoring engineers, architecting robust internal tools, and optimizing",
  "  engineering lifecycles for maximum productivity.",
  "",
  "SKILLS",
  "  Frontend:        JavaScript, TypeScript, React, Redux, Jest, React Testing Library,",
  "                   REST, WebSockets, Webpack, Vite",
  "  Backend:         NodeJS, Ruby on Rails, Python, Django, GraphQL, API Design,",
  "                   MySQL, Postgres, AWS, CI/CD",
  "  AI & Automation: LLMs, Claude Code, AI Agents, MCP, Prompt Engineering",
  "",
  "EXPERIENCE",
  "",
  "  Jan 2024 - Apr 2025  ·  SENIOR FULL-STACK ENGINEER",
  "  Mixpanel  (mixpanel.com)  — events-based data analytics platform",
  "  • Architected and led the high-impact warehouse connectors initiative, enabling",
  "    5,000+ enterprise customers to sync Databricks, Redshift, BigQuery, and",
  "    Snowflake with Mixpanel. Engineered full stack: React, Python/Django, MySQL.",
  "  • Directly generated 7% of total company revenue by scaling the platform to",
  "    handle over 5,000 successful automated event imports.",
  "  • Designed and deployed a data validation pipeline for safe staging and",
  "    upgrading of event subsets to full production imports.",
  "  • Directed the technical roadmap and agile execution, cross-functionally leading",
  "    product and design teams to deliver scalable data integration solutions.",
  "",
  "  Mar 2021 - Oct 2023  ·  SENIOR SOFTWARE ENGINEER",
  "  Affirm  (affirm.com)  — Buy Now Pay Later leader",
  "  • Built brand-new savings account web experience, adding millions in assets.",
  "  • Created promotion module → +26% gross merchandise volume on average.",
  "  • Reduced tech debt by separating data/view logic with custom React hooks;",
  "    added ESLint and TypeScript checks to pull requests.",
  "  • Led 3-engineer team building internal tools for 200k rewards customers.",
  "    Authored tech specs, estimates, code reviews, project updates, and UAT.",
  "  • Ran four experiments on the main shop feed generating 30% of company revenue.",
  "",
  "  Mar 2019 - Oct 2020  ·  SENIOR SOFTWARE ENGINEER",
  "  Shape Security  (acquired by F5)  — bot-detection and fraud-prevention",
  "  • Engineered and maintained a React-based design system and component library,",
  "    accelerating development velocity across three distinct product lines.",
  "  • Launched an internal web-based IDE via NPM, enabling enterprise customers to",
  "    safely modify configurations within management applications.",
  "  • Standardized the engineering lifecycle (design docs, code reviews, testing),",
  "    resulting in measurably higher code quality and team productivity.",
  "  • Implemented automated error logging across the product suite.",
  "  • Mentored four junior engineers, fostering technical growth and best practices.",
  "",
  "  Jan 2018 - Jan 2019  ·  SENIOR SOFTWARE ENGINEER",
  "  Manifold Technology  — blockchain-based enterprise transaction infrastructure",
  "  • Owned the end-to-end web frontend architecture: design, styling, deployment.",
  "  • Architected and scaled diverse web apps: commodities exchange, influencer",
  "    marketplace, and merchant rewards portal.",
  "  • Standardized frontend workflows: style guides, linters, CI/CD pipelines.",
  "  • Ensured product reliability with automated unit and integration test suites.",
  "",
  "  Nov 2014 - Sep 2017  ·  SOFTWARE ENGINEER",
  "  Wealthfront  (wealthfront.com)  — online financial advisor",
  "  • Led the successful launch of college savings accounts and Advanced Indexing",
  "    projects, driving millions of dollars in new investments.",
  "  • Optimized signup flow through data analysis → +14% traffic.",
  "",
  "  Apr 2012 - Feb 2014  ·  APPLICATION SUPPORT ENGINEER",
  "  Epic  (epic.com)  — healthcare IT covering 50%+ of US patients",
  "  • Developed 40 documented fixes for the Epic 2014 release and managed a",
  "    Russian localization team of 10.",
  "",
  "PERSONAL PROJECTS",
  "  DrummaLlama         https://github.com/ytolstyk/advanced-metronome",
  "    Advanced metronome and beat looper built with Claude Code.",
  "  Saltmarsh Timeline   https://github.com/ytolstyk/saltmarsh-timeline",
  "    DnD events timeline. React, GraphQL.",
  "  Eat-a-Burrita        https://github.com/ytolstyk/eataburrita-native",
  "    Burrito locator app. Kotlin, Jetpack Compose.",
  "  Battle Dice          https://github.com/ytolstyk/battle-dice-server",
  "    Real-time multiplayer dice game using WebSockets.",
  "",
  "EDUCATION",
  "  Full-stack Web Development (2014)  —  App Academy, San Francisco, CA",
  "  MS Mathematics (2012)              —  California State University East Bay",
  "",
  "INTERESTS",
  "  Game development (UE5), Android apps, cycling, playing guitar, photography, painting",
];

export function resume(): CommandResult {
  return {
    lines: [
      { type: "system", content: "==> resume.txt <==" },
      { type: "output", content: "" },
      ...RESUME_LINES.map((line) => ({
        type: "output" as const,
        content: line,
      })),
    ],
  };
}
