import type { CommandResult } from "@/types/terminal";

const RESUME_LINES = [
  "YURIY TOLSTYKH",
  "Senior Software Engineer — San Jose, CA",
  "408-726-1215  •  github.com/ytolstyk  •  yuriy.tolstykh@gmail.com",
  "",
  "SUMMARY",
  "  I build delightful customer-facing apps and features focusing on API design",
  "  and UI. Expert in web front-end, especially React. I prefer ownership of the",
  "  codebase and a collaborative cross-functional team.",
  "",
  "SKILLS",
  "  Frontend:  JavaScript, TypeScript, React, Redux, Jest, RTL, REST,",
  "             WebSockets, HTML, CSS, Webpack, Vite",
  "  Backend:   NodeJS, Socket.IO, Ruby on Rails, Python, Django, MySQL, Postgres",
  "  AI:        Claude Code, Skills, MCP",
  "",
  "EXPERIENCE",
  "",
  "  Jan 2024 - Apr 2025  ·  SENIOR FULL-STACK ENGINEER",
  "  Mixpanel  (mixpanel.com)  — events-based data analytics platform",
  "  • Led warehouse connectors project (Databricks, Redshift, BigQuery, Snowflake)",
  "    full-stack: React, Python/Django, MySQL — drives 7% of total revenue.",
  "  • Designed test imports feature for safe small-dataset validation.",
  "  • Collaborated with infra, product, and design to ship new features.",
  "",
  "  Mar 2021 - Oct 2023  ·  SENIOR SOFTWARE ENGINEER",
  "  Affirm  (affirm.com)  — Buy Now Pay Later leader",
  "  • Built brand-new savings account web experience, adding millions in assets.",
  "  • Created promotion module → +26% gross merchandise volume on average.",
  "  • Reduced tech debt with custom React hooks; added ESLint + TS to CI.",
  "  • Led 3-engineer team building internal tools for 200k rewards customers.",
  "  • Shipped four shop-feed projects driving 30% of company revenue.",
  "",
  "  Mar 2019 - Oct 2020  ·  SENIOR SOFTWARE ENGINEER",
  "  Shape Security  — bot-detection and fraud-prevention",
  "  • Created a React component library adopted across three products.",
  "  • Packaged an internal web IDE, integrated into customer-facing management app.",
  "  • Standardized design docs, code reviews, testing, standups, retrospectives.",
  "  • Added error logging to three products; mentored four junior engineers.",
  "",
  "  Jan 2018 - Jan 2019  ·  SENIOR SOFTWARE ENGINEER",
  "  Manifold Technology  — blockchain-based enterprise transaction infrastructure",
  "  • Owned entire web front-end: styling, architecture, deployment.",
  "  • Built commodities exchange app, influencer platform, merchant rewards portal.",
  "  • Established front-end workflow, style guide, linters, and deployment process.",
  "",
  "  Nov 2014 - Sep 2017  ·  SOFTWARE ENGINEER",
  "  Wealthfront  (wealthfront.com)  — online financial advisor",
  "  • Built college savings accounts product with team of 4; millions raised month 1.",
  "  • Led Advanced Indexing project for custom experiences at investment tiers.",
  "  • Improved signup flow via data analysis → +14% traffic.",
  "",
  "  Apr 2012 - Feb 2014  ·  APPLICATION SUPPORT ENGINEER",
  "  Epic  (epic.com)  — healthcare IT covering 50%+ of US patients",
  "  • Shipped 40 fixes/enhancements in Epic 2014 release (top 5 of 90).",
  "  • Managed Russian localization team of 10.",
  "",
  "PERSONAL PROJECTS",
  "  DrummaLlama        https://github.com/ytolstyk/advanced-metronome",
  "    Drum beat looper & metronome. React, Tailwind, Claude Code.",
  "  Saltmarsh Timeline  https://github.com/ytolstyk/saltmarsh-timeline",
  "    DnD events timeline. React, TypeScript, AWS Amplify, Cognito, GraphQL.",
  "  Eat-a-Burrita       https://github.com/ytolstyk/eataburrita-native",
  "    Android burrito-spot tracker. Kotlin, Jetpack Compose, Google Maps API.",
  "  Battle Dice         https://github.com/ytolstyk/battle-dice-server",
  "    Real-time dice battles. WebSockets, NodeJS, hosted on AWS and Render.",
  "",
  "EDUCATION",
  "  Full-stack Web Development (2014)  —  App Academy, San Francisco, CA",
  "  MS Mathematics (2012)              —  California State University East Bay",
  "",
  "INTERESTS",
  "  Game development with UE5, Android apps, cycling, guitar, photography, painting",
];

export function resume(): CommandResult {
  return {
    lines: [
      { type: "system", content: "==> resume.txt <==" },
      { type: "output", content: "" },
      ...RESUME_LINES.map((line) => ({
        type: "output" as const,
        content: line,
      })),
    ],
  };
}
